### ISSUE TITLE
Investigate JS unit test failure in `PasteStatus.createPasteNotification()`

### ISSUE THREAD

**Issue by elrido** [PrivateBin/PrivateBin#1139]
Noticed in https://github.com/PrivateBin/PrivateBin/actions/runs/5796192270/job/15709234100 - our property based unit testing fails in one test in a reproducible fashion.

## Steps to reproduce

```console
$ cd PrivateBin/js
$ mocha test --jsverifyRngState 87ab3f64de258190c7
```

### What happens

```console
[...]

  96 passing (30s)
  1 failing

  1) PasteStatus
       createPasteNotification
         creates a notification after a successfull paste upload:
     Error: Failed after 67 tests and 10 shrinks. rngState: 87ab3f64de258190c7; Counterexample: "ftp"; ["l"]; []; ""; "ftp"; ["f"]; ["a", "&", "g", "t"]; 
      at /home/runner/work/PrivateBin/PrivateBin/js/node_modules/jsverify/lib/jsverify.js:360:15
      at Object.map (node_modules/jsverify/lib/functor.js:35:12)
      at checkThrow (node_modules/jsverify/lib/jsverify.js:354:30)
      at Context.<anonymous> (node_modules/jsverify/lib/jsverify.js:400:14)
      at processImmediate (node:internal/timers:466:21)
```

### What should happen

```console
[...]

  97 passing (30s)
```
## Additional information

May be a false positive and require that the test or the generated data gets amended. Clearly is a corner case as we haven't seen this test failing before. From the looks of it, must be related with ftp:// URLs or that the sequence `&gt` that appears in it and isn't properly escaped, or it does get escaped and the test fails because it can't find the expected output.

Needs looking into what the test tries to do:
https://github.com/PrivateBin/PrivateBin/blob/3513d1802991e930924760768f9c5b93b827f573/js/test/PasteStatus.js#L8-L35

Given the parameter order, the counterexample translates to these inputs:

```javascript
schema1 = "ftp";
address1 = ["l"];
query1 = [];
fragment1 = "";
schema2 = "ftp";
address2 = ["f"];
query2 = ["a", "&", "g", "t"];
```

**Comment by elrido** [comment]
In https://github.com/PrivateBin/PrivateBin/actions/runs/6178274924/job/16771220455?pr=1173 we have got another example in the same area:

```
  96 passing (33s)
  1 failing

  1) PasteStatus
       createPasteNotification
         creates a notification after a successfull paste upload:
     Error: Failed after 52 tests and 12 shrinks. rngState: 827cfa12458e96d0b3; Counterexample: "ftp"; ["s"]; ["a", "&", "g", "t"]; ""; "ftp"; ["m"]; []; 
```
So a different seed, but ends up with the same schemas and the sequence `["a", "&", "g", "t"]` now is in the first query, not the second. The test will stitch these together as the following URLs (it would strip "&" characters at start and end of the query, but otherwise leave them be):
- rngState: 87ab3f64de258190c7:
  - `ftp://l/?#`
  - `ftp://f/?a&gt#`
- rngState: 827cfa12458e96d0b3:
  - `ftp://s/?a&gt#`
  - `ftp://m/?#`

I can't help but notice that `&gt;` is the HTML entity for the greater than sign. The ampersand in the URL should have gotten escaped, so the resulting URL should end up looking like `ftp://s/?a&amp;gt#` - if that is the case, the test would need to be extended in line 32 to do that replacement in the expected values as well.
