### ISSUE TITLE
Recurring errors with the creation of pastes

### ISSUE THREAD

**Issue by Rutaa** [PrivateBin/PrivateBin#1214]
**Did you use the FAQ section?**
- [x] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

### What happens
I've been having some problems creating pastes. Sometimes it succeeds the first time, more often the second-third time.

## Additional information
I have performed the following steps, unfortunately they did not bring any improvement.
Update apache, php to version 8 with libraries, migration to php-fpm
**Log from server:**
```
[Tue Dec 12 01:03:56.509962 2023] [proxy_fcgi:error] [pid 59071] [client x] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: A JSON error occurred: Syntax error (4) in /var/www/html/PrivateBin/lib/Json.php:76\nStack trace:\n#0 /var/www/html/PrivateBin/lib/Json.php(52): PrivateBin\\Json::_detectError()\n#1 /var/www/html/PrivateBin/lib/Data/Filesystem.php(347): PrivateBin\\Json::decode()\n#2 /var/www/html/PrivateBin/lib/Data/Filesystem.php(113): PrivateBin\\Data\\Filesystem->_get()\n#3 /var/www/html/PrivateBin/lib/Data/Filesystem.php(373): PrivateBin\\Data\\Filesystem->read()\n#4 /var/www/html/PrivateBin/lib/Data/AbstractData.php(158): PrivateBin\\Data\\Filesystem->_getExpiredPastes()\n#5 /var/www/html/PrivateBin/lib/Model.php(72): PrivateBin\\Data\\AbstractData->purge()\n#6 /var/www/html/PrivateBin/lib/Controller.php(253): PrivateBin\\Model->purge()\n#7 /var/www/html/PrivateBin/lib/Controller.php(125): PrivateBin\\Controller->_create()\n#8 /var/www/html/PrivateBin/index.php(18): PrivateBin\\Controller->__construct()\n#9 {main}\n  thrown in /var/www/html/PrivateBin/lib/Json.php on line 76'
[Tue Dec 12 01:37:04.655743 2023] [proxy_fcgi:error] [pid 59071] [client x] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: A JSON error occurred: Syntax error (4) in /var/www/html/PrivateBin/lib/Json.php:76\nStack trace:\n#0 /var/www/html/PrivateBin/lib/Json.php(52): PrivateBin\\Json::_detectError()\n#1 /var/www/html/PrivateBin/lib/Data/Filesystem.php(347): PrivateBin\\Json::decode()\n#2 /var/www/html/PrivateBin/lib/Data/Filesystem.php(113): PrivateBin\\Data\\Filesystem->_get()\n#3 /var/www/html/PrivateBin/lib/Data/Filesystem.php(373): PrivateBin\\Data\\Filesystem->read()\n#4 /var/www/html/PrivateBin/lib/Data/AbstractData.php(158): PrivateBin\\Data\\Filesystem->_getExpiredPastes()\n#5 /var/www/html/PrivateBin/lib/Model.php(72): PrivateBin\\Data\\AbstractData->purge()\n#6 /var/www/html/PrivateBin/lib/Controller.php(253): PrivateBin\\Model->purge()\n#7 /var/www/html/PrivateBin/lib/Controller.php(125): PrivateBin\\Controller->_create()\n#8 /var/www/html/PrivateBin/index.php(18): PrivateBin\\Controller->__construct()\n#9 {main}\n  thrown in /var/www/html/PrivateBin/lib/Json.php on line 76'
[Tue Dec 12 01:45:13.473810 2023] [proxy_fcgi:error] [pid 59236] [client x] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: A JSON error occurred: Syntax error (4) in /var/www/html/PrivateBin/lib/Json.php:76\nStack trace:\n#0 /var/www/html/PrivateBin/lib/Json.php(52): PrivateBin\\Json::_detectError()\n#1 /var/www/html/PrivateBin/lib/Data/Filesystem.php(347): PrivateBin\\Json::decode()\n#2 /var/www/html/PrivateBin/lib/Data/Filesystem.php(113): PrivateBin\\Data\\Filesystem->_get()\n#3 /var/www/html/PrivateBin/lib/Data/Filesystem.php(373): PrivateBin\\Data\\Filesystem->read()\n#4 /var/www/html/PrivateBin/lib/Data/AbstractData.php(158): PrivateBin\\Data\\Filesystem->_getExpiredPastes()\n#5 /var/www/html/PrivateBin/lib/Model.php(72): PrivateBin\\Data\\AbstractData->purge()\n#6 /var/www/html/PrivateBin/lib/Controller.php(253): PrivateBin\\Model->purge()\n#7 /var/www/html/PrivateBin/lib/Controller.php(125): PrivateBin\\Controller->_create()\n#8 /var/www/html/PrivateBin/index.php(18): PrivateBin\\Controller->__construct()\n#9 {main}\n  thrown in /var/www/html/PrivateBin/lib/Json.php on line 76'
[Tue Dec 12 02:11:29.000824 2023] [proxy_fcgi:error] [pid 59411] [client x] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: A JSON error occurred: Syntax error (4) in /var/www/html/PrivateBin/lib/Json.php:76\nStack trace:\n#0 /var/www/html/PrivateBin/lib/Json.php(52): PrivateBin\\Json::_detectError()\n#1 /var/www/html/PrivateBin/lib/Data/Filesystem.php(347): PrivateBin\\Json::decode()\n#2 /var/www/html/PrivateBin/lib/Data/Filesystem.php(113): PrivateBin\\Data\\Filesystem->_get()\n#3 /var/www/html/PrivateBin/lib/Data/Filesystem.php(373): PrivateBin\\Data\\Filesystem->read()\n#4 /var/www/html/PrivateBin/lib/Data/AbstractData.php(158): PrivateBin\\Data\\Filesystem->_getExpiredPastes()\n#5 /var/www/html/PrivateBin/lib/Model.php(72): PrivateBin\\Data\\AbstractData->purge()\n#6 /var/www/html/PrivateBin/lib/Controller.php(253): PrivateBin\\Model->purge()\n#7 /var/www/html/PrivateBin/lib/Controller.php(125): PrivateBin\\Controller->_create()\n#8 /var/www/html/PrivateBin/index.php(18): PrivateBin\\Controller->__construct()\n#9 {main}\n  thrown in /var/www/html/PrivateBin/lib/Json.php on line 76'
[Tue Dec 12 03:05:24.393197 2023] [proxy_fcgi:error] [pid 58987] [client x] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: A JSON error occurred: Syntax error (4) in /var/www/html/PrivateBin/lib/Json.php:76\nStack trace:\n#0 /var/www/html/PrivateBin/lib/Json.php(52): PrivateBin\\Json::_detectError()\n#1 /var/www/html/PrivateBin/lib/Data/Filesystem.php(347): PrivateBin\\Json::decode()\n#2 /var/www/html/PrivateBin/lib/Data/Filesystem.php(113): PrivateBin\\Data\\Filesystem->_get()\n#3 /var/www/html/PrivateBin/lib/Data/Filesystem.php(373): PrivateBin\\Data\\Filesystem->read()\n#4 /var/www/html/PrivateBin/lib/Data/AbstractData.php(158): PrivateBin\\Data\\Filesystem->_getExpiredPastes()\n#5 /var/www/html/PrivateBin/lib/Model.php(72): PrivateBin\\Data\\AbstractData->purge()\n#6 /var/www/html/PrivateBin/lib/Controller.php(253): PrivateBin\\Model->purge()\n#7 /var/www/html/PrivateBin/lib/Controller.php(125): PrivateBin\\Controller->_create()\n#8 /var/www/html/PrivateBin/index.php(18): PrivateBin\\Controller->__construct()\n#9 {main}\n  thrown in /var/www/html/PrivateBin/lib/Json.php on line 76'
[Tue Dec 12 03:05:27.275084 2023] [proxy_fcgi:error] [pid 59424] [client x] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: A JSON error occurred: Syntax error (4) in /var/www/html/PrivateBin/lib/Json.php:76\nStack trace:\n#0 /var/www/html/PrivateBin/lib/Json.php(52): PrivateBin\\Json::_detectError()\n#1 /var/www/html/PrivateBin/lib/Data/Filesystem.php(347): PrivateBin\\Json::decode()\n#2 /var/www/html/PrivateBin/lib/Data/Filesystem.php(113): PrivateBin\\Data\\Filesystem->_get()\n#3 /var/www/html/PrivateBin/lib/Data/Filesystem.php(373): PrivateBin\\Data\\Filesystem->read()\n#4 /var/www/html/PrivateBin/lib/Data/AbstractData.php(158): PrivateBin\\Data\\Filesystem->_getExpiredPastes()\n#5 /var/www/html/PrivateBin/lib/Model.php(72): PrivateBin\\Data\\AbstractData->purge()\n#6 /var/www/html/PrivateBin/lib/Controller.php(253): PrivateBin\\Model->purge()\n#7 /var/www/html/PrivateBin/lib/Controller.php(125): PrivateBin\\Controller->_create()\n#8 /var/www/html/PrivateBin/index.php(18): PrivateBin\\Controller->__construct()\n#9 {main}\n  thrown in /var/www/html/PrivateBin/lib/Json.php on line 76'
[Tue Dec 12 03:31:53.328087 2023] [proxy_fcgi:error] [pid 59425] [client x] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: A JSON error occurred: Syntax error (4) in /var/www/html/PrivateBin/lib/Json.php:76\nStack trace:\n#0 /var/www/html/PrivateBin/lib/Json.php(52): PrivateBin\\Json::_detectError()\n#1 /var/www/html/PrivateBin/lib/Data/Filesystem.php(347): PrivateBin\\Json::decode()\n#2 /var/www/html/PrivateBin/lib/Data/Filesystem.php(113): PrivateBin\\Data\\Filesystem->_get()\n#3 /var/www/html/PrivateBin/lib/Data/Filesystem.php(373): PrivateBin\\Data\\Filesystem->read()\n#4 /var/www/html/PrivateBin/lib/Data/AbstractData.php(158): PrivateBin\\Data\\Filesystem->_getExpiredPastes()\n#5 /var/www/html/PrivateBin/lib/Model.php(72): PrivateBin\\Data\\AbstractData->purge()\n#6 /var/www/html/PrivateBin/lib/Controller.php(253): PrivateBin\\Model->purge()\n#7 /var/www/html/PrivateBin/lib/Controller.php(125): PrivateBin\\Controller->_create()\n#8 /var/www/html/PrivateBin/index.php(18): PrivateBin\\Controller->__construct()\n#9 {main}\n  thrown in /var/www/html/PrivateBin/lib/Json.php on line 76'
[Tue Dec 12 03:39:02.852156 2023] [proxy_fcgi:error] [pid 58993] [client x] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: A JSON error occurred: Syntax error (4) in /var/www/html/PrivateBin/lib/Json.php:76\nStack trace:\n#0 /var/www/html/PrivateBin/lib/Json.php(52): PrivateBin\\Json::_detectError()\n#1 /var/www/html/PrivateBin/lib/Data/Filesystem.php(347): PrivateBin\\Json::decode()\n#2 /var/www/html/PrivateBin/lib/Data/Filesystem.php(113): PrivateBin\\Data\\Filesystem->_get()\n#3 /var/www/html/PrivateBin/lib/Data/Filesystem.php(373): PrivateBin\\Data\\Filesystem->read()\n#4 /var/www/html/PrivateBin/lib/Data/AbstractData.php(158): PrivateBin\\Data\\Filesystem->_getExpiredPastes()\n#5 /var/www/html/PrivateBin/lib/Model.php(72): PrivateBin\\Data\\AbstractData->purge()\n#6 /var/www/html/PrivateBin/lib/Controller.php(253): PrivateBin\\Model->purge()\n#7 /var/www/html/PrivateBin/lib/Controller.php(125): PrivateBin\\Controller->_create()\n#8 /var/www/html/PrivateBin/index.php(18): PrivateBin\\Controller->__construct()\n#9 {main}\n  thrown in /var/www/html/PrivateBin/lib/Json.php on line 76'
[Tue Dec 12 03:49:24.388040 2023] [proxy_fcgi:error] [pid 58987] [client x] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: A JSON error occurred: Syntax error (4) in /var/www/html/PrivateBin/lib/Json.php:76\nStack trace:\n#0 /var/www/html/PrivateBin/lib/Json.php(52): PrivateBin\\Json::_detectError()\n#1 /var/www/html/PrivateBin/lib/Data/Filesystem.php(347): PrivateBin\\Json::decode()\n#2 /var/www/html/PrivateBin/lib/Data/Filesystem.php(113): PrivateBin\\Data\\Filesystem->_get()\n#3 /var/www/html/PrivateBin/lib/Data/Filesystem.php(373): PrivateBin\\Data\\Filesystem->read()\n#4 /var/www/html/PrivateBin/lib/Data/AbstractData.php(158): PrivateBin\\Data\\Filesystem->_getExpiredPastes()\n#5 /var/www/html/PrivateBin/lib/Model.php(72): PrivateBin\\Data\\AbstractData->purge()\n#6 /var/www/html/PrivateBin/lib/Controller.php(253): PrivateBin\\Model->purge()\n#7 /var/www/html/PrivateBin/lib/Controller.php(125): PrivateBin\\Controller->_create()\n#8 /var/www/html/PrivateBin/index.php(18): PrivateBin\\Controller->__construct()\n#9 {main}\n  thrown in /var/www/html/PrivateBin/lib/Json.php on line 76'
[Tue Dec 12 06:17:44.521168 2023] [proxy_fcgi:error] [pid 59253] [client x] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: A JSON error occurred: Syntax error (4) in /var/www/html/PrivateBin/lib/Json.php:76\nStack trace:\n#0 /var/www/html/PrivateBin/lib/Json.php(52): PrivateBin\\Json::_detectError()\n#1 /var/www/html/PrivateBin/lib/Data/Filesystem.php(347): PrivateBin\\Json::decode()\n#2 /var/www/html/PrivateBin/lib/Data/Filesystem.php(113): PrivateBin\\Data\\Filesystem->_get()\n#3 /var/www/html/PrivateBin/lib/Data/Filesystem.php(373): PrivateBin\\Data\\Filesystem->read()\n#4 /var/www/html/PrivateBin/lib/Data/AbstractData.php(158): PrivateBin\\Data\\Filesystem->_getExpiredPastes()\n#5 /var/www/html/PrivateBin/lib/Model.php(72): PrivateBin\\Data\\AbstractData->purge()\n#6 /var/www/html/PrivateBin/lib/Controller.php(253): PrivateBin\\Model->purge()\n#7 /var/www/html/PrivateBin/lib/Controller.php(125): PrivateBin\\Controller->_create()\n#8 /var/www/html/PrivateBin/index.php(18): PrivateBin\\Controller->__construct()\n#9 {main}\n  thrown in /var/www/html/PrivateBin/lib/Json.php on line 76'
[Tue Dec 12 06:17:46.659130 2023] [proxy_fcgi:error] [pid 59425] [client x] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: A JSON error occurred: Syntax error (4) in /var/www/html/PrivateBin/lib/Json.php:76\nStack trace:\n#0 /var/www/html/PrivateBin/lib/Json.php(52): PrivateBin\\Json::_detectError()\n#1 /var/www/html/PrivateBin/lib/Data/Filesystem.php(347): PrivateBin\\Json::decode()\n#2 /var/www/html/PrivateBin/lib/Data/Filesystem.php(113): PrivateBin\\Data\\Filesystem->_get()\n#3 /var/www/html/PrivateBin/lib/Data/Filesystem.php(373): PrivateBin\\Data\\Filesystem->read()\n#4 /var/www/html/PrivateBin/lib/Data/AbstractData.php(158): PrivateBin\\Data\\Filesystem->_getExpiredPastes()\n#5 /var/www/html/PrivateBin/lib/Model.php(72): PrivateBin\\Data\\AbstractData->purge()\n#6 /var/www/html/PrivateBin/lib/Controller.php(253): PrivateBin\\Model->purge()\n#7 /var/www/html/PrivateBin/lib/Controller.php(125): PrivateBin\\Controller->_create()\n#8 /var/www/html/PrivateBin/index.php(18): PrivateBin\\Controller->__construct()\n#9 {main}\n  thrown in /var/www/html/PrivateBin/lib/Json.php on line 76'
[Tue Dec 12 06:56:58.172051 2023] [proxy_fcgi:error] [pid 70370] [client x] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: A JSON error occurred: Syntax error (4) in /var/www/html/PrivateBin/lib/Json.php:76\nStack trace:\n#0 /var/www/html/PrivateBin/lib/Json.php(52): PrivateBin\\Json::_detectError()\n#1 /var/www/html/PrivateBin/lib/Data/Filesystem.php(347): PrivateBin\\Json::decode()\n#2 /var/www/html/PrivateBin/lib/Data/Filesystem.php(113): PrivateBin\\Data\\Filesystem->_get()\n#3 /var/www/html/PrivateBin/lib/Data/Filesystem.php(373): PrivateBin\\Data\\Filesystem->read()\n#4 /var/www/html/PrivateBin/lib/Data/AbstractData.php(158): PrivateBin\\Data\\Filesystem->_getExpiredPastes()\n#5 /var/www/html/PrivateBin/lib/Model.php(72): PrivateBin\\Data\\AbstractData->purge()\n#6 /var/www/html/PrivateBin/lib/Controller.php(253): PrivateBin\\Model->purge()\n#7 /var/www/html/PrivateBin/lib/Controller.php(125): PrivateBin\\Controller->_create()\n#8 /var/www/html/PrivateBin/index.php(18): PrivateBin\\Controller->__construct()\n#9 {main}\n  thrown in /var/www/html/PrivateBin/lib/Json.php on line 76'
[Tue Dec 12 07:17:00.004029 2023] [proxy_fcgi:error] [pid 58993] [client x] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: A JSON error occurred: Syntax error (4) in /var/www/html/PrivateBin/lib/Json.php:76\nStack trace:\n#0 /var/www/html/PrivateBin/lib/Json.php(52): PrivateBin\\Json::_detectError()\n#1 /var/www/html/PrivateBin/lib/Data/Filesystem.php(347): PrivateBin\\Json::decode()\n#2 /var/www/html/PrivateBin/lib/Data/Filesystem.php(113): PrivateBin\\Data\\Filesystem->_get()\n#3 /var/www/html/PrivateBin/lib/Data/Filesystem.php(373): PrivateBin\\Data\\Filesystem->read()\n#4 /var/www/html/PrivateBin/lib/Data/AbstractData.php(158): PrivateBin\\Data\\Filesystem->_getExpiredPastes()\n#5 /var/www/html/PrivateBin/lib/Model.php(72): PrivateBin\\Data\\AbstractData->purge()\n#6 /var/www/html/PrivateBin/lib/Controller.php(253): PrivateBin\\Model->purge()\n#7 /var/www/html/PrivateBin/lib/Controller.php(125): PrivateBin\\Controller->_create()\n#8 /var/www/html/PrivateBin/index.php(18): PrivateBin\\Controller->__construct()\n#9 {main}\n  thrown in /var/www/html/PrivateBin/lib/Json.php on line 76'
```
**Log from browser:**
![image](https://github.com/PrivateBin/PrivateBin/assets/26909103/97b74157-89eb-4990-aba6-7e95e17bee50)
## Basic information
Server OS: Ubuntu
Webserver: Apache
Browser: ALL
PrivateBin version: 1.6.1
I can reproduce this issue on <https://privatebin.net>:  No

**Comment by elrido** [comment]
The JSON errors usually occur when the payload arriving in PHP is incomplete. This may occur due to some networking issue, but most likely it is an inconsistency between the [different settings that limit the maximum POST request size & memory usage at the reverse-proxy, webserver and PHP runtime levels](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#sizelimit). Do the errors occur more reproducibly if larger pastes / attachements are sent? Can you reproduce it every time with certain payloads?

One other problem source can be reverse-proxy services with security solutions, like cloudflare. These might break the JSON as well - if using one of these, try bypassing them and see if this resolves the problem.

**Comment by Rutaa** [comment]
We do not use reverse-proxy and the memory limit is set to 256M. The error occurs regardless of the size of the paste. The problem also occurs when I run the administration script. The log looks as follows:
`root@pb:/var/www/html/PrivateBin/bin# php administration -p
PHP Fatal error:  Uncaught Exception: A JSON error occurred: Syntax error (4) in /var/www/html/PrivateBin/lib/Json.php:76
Stack trace:
#0 /var/www/html/PrivateBin/lib/Json.php(52): PrivateBin\Json::_detectError()
#1 /var/www/html/PrivateBin/lib/Data/Filesystem.php(347): PrivateBin\Json::decode()
#2 /var/www/html/PrivateBin/lib/Data/Filesystem.php(113): PrivateBin\Data\Filesystem->_get()
#3 /var/www/html/PrivateBin/lib/Data/Filesystem.php(373): PrivateBin\Data\Filesystem->read()
#4 /var/www/html/PrivateBin/lib/Data/AbstractData.php(158): PrivateBin\Data\Filesystem->_getExpiredPastes()
#5 /var/www/html/PrivateBin/bin/administration(308): PrivateBin\Data\AbstractData->purge()
#6 /var/www/html/PrivateBin/bin/administration(318): PrivateBin\Administration->__construct()
#7 {main}
  thrown in /var/www/html/PrivateBin/lib/Json.php on line 76
root@pb:/var/www/html/PrivateBin/bin# php administration -s
Total:                  1136
PHP Fatal error:  Uncaught Exception: A JSON error occurred: Syntax error (4) in /var/www/html/PrivateBin/lib/Json.php:76
Stack trace:
#0 /var/www/html/PrivateBin/lib/Json.php(52): PrivateBin\Json::_detectError()
#1 /var/www/html/PrivateBin/lib/Data/Filesystem.php(347): PrivateBin\Json::decode()
#2 /var/www/html/PrivateBin/lib/Data/Filesystem.php(113): PrivateBin\Data\Filesystem->_get()
#3 /var/www/html/PrivateBin/bin/administration(220): PrivateBin\Data\Filesystem->read()
#4 /var/www/html/PrivateBin/bin/administration(313): PrivateBin\Administration->_statistics()
#5 /var/www/html/PrivateBin/bin/administration(318): PrivateBin\Administration->__construct()
#6 {main}
  thrown in /var/www/html/PrivateBin/lib/Json.php on line 76
`

**Comment by elrido** [comment]
Ok, that it occurs every time when using the administration script is a great clue! The one other thing that gets triggered only during creating is the purging of old pastes. For this, a number of random pastes are selected and checked. So what might be going on is that one of the pastes on disk got corrupted, and this causes the issue when it gets accessed.

### Finding the affected paste(s)

If you add a `var_dump($pasteid);` between these two lines:
https://github.com/PrivateBin/PrivateBin/blob/9b07e3ff62166a49c3ecb12e4feddb45754f6457/bin/administration#L219-L220

...and re-run the statistics, it should display every pasteid before it reads it - the problematic paste will show up as the last item before the exception is thrown. You can either fix it (restore it from backup, for example) or just delete it (using the administration script). You may have to repeat this a few times, should multiple pastes be affected.

I'll consider adding a try-catch block down the line, so we can report which paste is affected and count how many broken pastes there are.

**Comment by elrido** [comment]
FYI, instead of the above suggestion with the var_dump, you may want to try the admin script from the above linked commit/PR which will list all damaged paste IDs and also count them.
