### ISSUE TITLE
Travis-CI JS unit tests fail

### ISSUE THREAD

**Issue by rugk** [PrivateBin/PrivateBin#229]
The unit tests on [Travis-CI](https://travis-ci.org/PrivateBin/PrivateBin/builds/231068952) fail while the ones on [Scrutinizer](https://scrutinizer-ci.com/g/PrivateBin/PrivateBin/inspections/4f100825-9343-487d-a0ce-13d2695a0475/log) work.

Only Mocha fails:
```
$ cd ../js && mocha

/home/travis/build/PrivateBin/PrivateBin/js/node_modules/jsdom/lib/api.js:10

const { URL } = require("whatwg-url");

      ^

SyntaxError: Unexpected token {

    at exports.runInThisContext (vm.js:53:16)

    at Module._compile (module.js:373:25)

    at Object.Module._extensions..js (module.js:416:10)

    at Module.load (module.js:343:32)

    at Function.Module._load (module.js:300:12)

    at Module.require (module.js:353:17)

    at require (internal/module.js:12:17)

    at globalJsdom (/home/travis/build/PrivateBin/PrivateBin/js/node_modules/jsdom-global/index.js:28:15)

    at Object.<anonymous> (/home/travis/build/PrivateBin/PrivateBin/js/test.js:4:15)

    at Module._compile (module.js:409:26)

    at Object.Module._extensions..js (module.js:416:10)

    at Module.load (module.js:343:32)

    at Function.Module._load (module.js:300:12)

    at Module.require (module.js:353:17)

    at require (internal/module.js:12:17)

    at /home/travis/.nvm/versions/node/v4.8.3/lib/node_modules/mocha/lib/mocha.js:230:27

    at Array.forEach (native)

    at Mocha.loadFiles (/home/travis/.nvm/versions/node/v4.8.3/lib/node_modules/mocha/lib/mocha.js:227:14)

    at Mocha.run (/home/travis/.nvm/versions/node/v4.8.3/lib/node_modules/mocha/lib/mocha.js:495:10)

    at Object.<anonymous> (/home/travis/.nvm/versions/node/v4.8.3/lib/node_modules/mocha/bin/_mocha:460:18)

    at Module._compile (module.js:409:26)

    at Object.Module._extensions..js (module.js:416:10)

    at Module.load (module.js:343:32)

    at Function.Module._load (module.js:300:12)

    at Function.Module.runMain (module.js:441:10)

    at startup (node.js:140:18)

    at node.js:1043:3

The command "cd ../js && mocha" exited with 1.
```

**Comment by rugk** [comment]
Okay, so the reason for the difference is that Scrutinizer does not execute the JS tests at all…

**Comment by elrido** [comment]
obviously JSDOM, which is used by Mocha to emulate a browser environment in nodeJS, introduced some kind of breaking change. I will see if they already have an issue for this or if there's a workaround.

**Comment by elrido** [comment]
Ok, found it: The latest JSDOM [does no longer support nodeJS < 6](https://github.com/tmpvar/jsdom/issues/1817). Version 4 is what is packaged on most Linux distributions at this time and what is also used by Travis. Hence we have to stick to older node packages for the time being. :-(

**Comment by elrido** [comment]
Merged this back into master, including the latest JS unit tests, so that the angry errors get away.
