### ISSUE TITLE
Old issue closed without being resolved.

### ISSUE THREAD

**Issue by tryingtosetup** [PrivateBin/PrivateBin#293]
Still get this same error

[:error] [pid 15084] [client 85.203.47.63:53007] PHP Fatal error:  Uncaught Exception: unable to create directory data in /var/www/html/PrivateBin/lib/Persistence/AbstractPersistence.php:88\nStack trace:\n#0 /var/www/html/PrivateBin/lib/Persistence/AbstractPersistence.php(72): PrivateBin\\Persistence\\AbstractPersistence::_initialize()\n#1 /var/www/html/PrivateBin/lib/Persistence/TrafficLimiter.php(104): PrivateBin\\Persistence\\AbstractPersistence::_exists('traffic_limiter...')\n#2 /var/www/html/PrivateBin/lib/PrivateBin.php(216): PrivateBin\\Persistence\\TrafficLimiter::canPass()\n#3 /var/www/html/PrivateBin/lib/PrivateBin.php(141): PrivateBin\\PrivateBin->_create()\n#4 /var/www/html/PrivateBin/index.php(18): PrivateBin\\PrivateBin->__construct()\n#5 {main}\n  thrown in /var/www/html/PrivateBin/lib/Persistence/AbstractPersistence.php on line 88

Even after running the script https://github.com/PrivateBin/PrivateBin/wiki/FAQ#what-are-the-recommended-file-and-folder-permissions-for-privatebin

So what can the issue be?

**Comment by rugk** [comment]
I'll answer you in your first thread. Next time, you can just comment on a closed issue. When an issue is closed on GitHub, it just means it is considered to be resolved (or so), you can still comment.
